import { type NextPage } from 'next'
import Head from 'next/head'
import NavBar from '@/components/NavBar'
import ProfileInfo from '@/components/ProfileInfo'
import { useEffect, useState } from 'react'
import { useAuthState } from 'react-firebase-hooks/auth'
import { auth, db } from '@/lib/firebase'
import { doc, getDoc, getDocs, collection } from 'firebase/firestore'


const Profile: NextPage = () => {

const [user] = useAuthState(auth)
const [username, setUsername] = useState("")
const [lifeTimeHours, setLifeTimeHours] = useState(0)
const [workTime, setWorkTime] = useState(0)
const [breakTime, setBreakTime] = useState(0)

useEffect(() => {
    if (user) {
        const docRef = doc(db, "users", user.uid)
        getDoc(docRef).then((doc) => {
            if (doc.exists()) {
                setUsername(doc.data().displayName)
                setWorkTime(doc.data().workTime)
                setBreakTime(doc.data().breakTime)
                getHours(user.uid)
            } else {
                console.log("No such document!")
            }
        }).catch((error) => {
            console.log("Error getting document:", error)
        })

        const getHours = async (id: string) => {
            const querySnapshot = await getDocs(collection(db, "users", id, "hours"))
            let hours = 0
            querySnapshot.forEach((doc) => {
                hours += doc.data().hours
            })
            setLifeTimeHours(parseFloat(hours.toFixed(2)))
        }
    }
}, [user])





    return (
        <>
            <Head>
                <title>Potato Timer</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <NavBar/>
           <div className="flex justify-center items-center ">
           <ProfileInfo name={username} lifeTimeHours={lifeTimeHours} workTime={workTime} breakTime={breakTime} />
           </div>
        </>
    )
}

export default Profile
